canary:
  deployments:
  - environment: production
    description: 'Canary'
    payload:
      release: production-myapp
      namespace: production
      track: canary
      values:
        replicaCount: 1

production:
  deployments:
  - environment: production
    task: remove
    description: 'Remove canary'
    payload:
      track: canary
      release: production-myapp
      namespace: production
  - environment: production
    description: 'Production'
    payload:
      release: production-myapp
      namespace: production
      track: stable
      values:
        replicaCount: 5
