name: 'Push'
on: ['push']

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: 'actions/checkout@v1'

    - name: 'Test'
      run: 'kubectl version'

    # - name: 'Build'
    #   run: 'docker build -t myapp .'
    # - name: 'Push'
    #   run: 'docker push myapp'
